title: "슈퍼파워 랩"
description: "당신의 뇌는 무엇에 보상하는가"
baseurl: "/superpower-lab"
url: "https://juliuschun.github.io"
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: "2..3"
permalink: /:title/
